name: Ping Render to Keep Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render Backend
        run: curl -i https://codex-website-backend.onrender.com/health
